# .github/workflows/deploy.yaml

name: Build and Deploy

on:
  push:
    branches: [deploy]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm ci
          npm run test:unit
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          target-folder: docs # Deploy into this folder in the target branch.
